### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by kersten** [Saquib764/dna-router#1]
Hi,

is the version unstable, or does not work at all? I get the error `Uncaught TypeError: Cannot read property 'route' of undefined` when I'm launching the app.

Did I miss anything?

Greetings

**Comment by kersten** [comment]
Ah ok, I think I found the error by my self. But I have to revalidate this.

**Comment by kersten** [comment]
Jup, had a slash in parent attribute.

**Comment by Saquib764** [comment]
Great. Element is not yet free of all errors. I'll update it once I have time.
Let me know if you have some suggestions :)
