### ISSUE TITLE
Bug in the template path in the dna-view element

### ISSUE THREAD

**Issue by halyson97** [Saquib764/dna-router#17]
The "_load_page" function in the dna-view element adds two "//" to the template path.

Code my element:
![captura de tela de 2018-01-09 16-33-58](https://user-images.githubusercontent.com/9968866/34736671-edf2f45a-f55a-11e7-9007-71224039513e.png)

Code dna-view element:
![captura de tela de 2018-01-09 16-28-49](https://user-images.githubusercontent.com/9968866/34736569-8cc47208-f55a-11e7-941e-7f2e1be97895.png)

Result:
![captura de tela de 2018-01-09 16-21-00](https://user-images.githubusercontent.com/9968866/34736594-a8e70b4e-f55a-11e7-80b3-da27587f083e.png)

**Comment by Saquib764** [comment]
Should work now. Thanks :+1:
