### ISSUE TITLE
dna-config

### ISSUE THREAD

**Issue by kersten** [Saquib764/dna-router#2]
Hi there,

could you please post a full example for using dna-config and setting auth state and so on?

I have a `/home` route with an login form on. This should be hidden after successful login and the `logged-in-view` template should be visible.

```
<dna-view state="home" element="home" template="\elements\home\home.html" auth="false"></dna-view>
<dna-view state="home" element="home-logged-in" template="\elements\home\home-logged-in.html" auth="true"></dna-view>
```

This was my try, but it did not work.

Thanks Kersten

**Comment by Saquib764** [comment]
Hi Kersten,
Try a different state name for logged in view. It should work.

Thanks.

**Comment by kersten** [comment]
But I can't register two new state on the same route like this:

```
<dna-new-state state="home" route='/home'></dna-new-state>
<dna-new-state state="home-logged-in" route='/home'></dna-new-state>
```

**Comment by Saquib764** [comment]
You can register multiple state name with same route. But while resolving URL, page will load state which get registered first. There is no check on routes.
You can use 'go('home-logged-in')' method in DnaStateProviderBehavior to navigate states.

What error message do you get?

**Comment by kersten** [comment]
ok, did not get an error :) how do i tell the router that the user was successfully authenticated?

**Comment by Saquib764** [comment]
On login, change 'dna-config'.status = true and then pass some user data 'dna-config'.user = {name: 'SOme name'}.

**Comment by kersten** [comment]
ah ok, yes! many thanks :D

**Comment by Saquib764** [comment]
Welcome :) :D

**Comment by kersten** [comment]
Silly question, how do I set the state. I did not get it running till yet :( I want to pass the logged in status from my php application. I tired it like this:

```
Polymer( {
    is: "my-app",
    behaviors: [DnaConfigBehavior],

    attached: function () {
        this.status = <?= ( $this->hasIdentity ) ? 'true' : 'false' ?>;
    }
} );
```

How would I do it correctly?

**Comment by Saquib764** [comment]
You just need to create a 'dna-config' tag. For authenticated page :
dna-config status='true' user=[{name: 'me'}]  /dna-config
