### ISSUE TITLE
params not passed to the view-element

### ISSUE THREAD

**Issue by fmcdev** [Saquib764/dna-router#6]
Unfortunally params don't work at all... they are not passed to the view element when the view is selected.
No way to access to the params - tried the following:
1)  this.params.id
2)  this.$state.params.id
3) this.$.state.params.id

Also it's difficult to inject dynamic param values into the goto attribute of s-ref anchors (no problems when using constants), because goto='["home",{ "id": "{{dynamicValue}}" }] seems not able to be resolved, causing an error on "replace" function in "dna behavior".

Also: please add examples/explanation how to use attach and behavior properties defined in the polymer constructor inside custom elements.

This way is not usable... that's a pitty because it could really be the best one with polymer!
:-(

**Comment by Saquib764** [comment]
Hi fmcdev,
Sorry for bad documentation. :(
You can access params via
$state.params.<your param key>

To go to some other state,
$state.go('some state', params)

PS: I am working on dynamic params part. Will be updating soon.

Thanks.
