### ISSUE TITLE
Providing View Context

### ISSUE THREAD

**Issue by patgmiller** [Saquib764/dna-router#7]
What plans do you have for providing a method to pass context to the view element? Will there be any  data binding attribute like `context="{{parentAttribue}}"` or do you expect those who use `dna-router` to handle it themselves with events or something?

For example, the router is able to handle routes like `/users/:name/` or `/order/:id/`, but the actual route parameter, `:name` or `:id` is not passed to the view element.

**Comment by Saquib764** [comment]
@patgmiller  Actually, you can access all parameters and route related data inside view.

See this issue: https://github.com/Saquib764/dna-router/issues/6

You can even access them outside view. There is a global variable '$params' that stores all params and context.

**Comment by patgmiller** [comment]
Thanks. I may not be on the latest, because there wasn't a `$params` global variable, but there is a `$state` global variable. 

What about passing a context from a parent element to the element of the `dna-view`? For example:

```
<dna-view state="users" element="users-page" context="{{extraContext}}"></dna-view>
```

**Comment by Saquib764** [comment]
Yes. It can be done, I have to make few changes.
But I don't see the how it can be usefull. 
Can you please point out some ways in which it will be useful?

**Comment by patgmiller** [comment]
Current I am working on an ecommerce order management app and with it there is the active user and their user role which determines their permissions and such. So for example it might be nice to pass that information. 

``` html
<dna-new-state state='users' element="users-list" route='/users'></dna-new-state>
<dna-new-state state='user-detail' element="user-detail" route='/users/:username/'></dna-new-state>
<dna-new-state state='orders' element="orders-list" route='/orders'></dna-new-state>
<dna-new-state state='order-detail' element="order-detail" route='/orders/:id/'></dna-new-state>

<dna-multi-view>
<!-- session could be {authuser: {username: 'someone', role: 'customer-service' }} -->
<dna-view state="users" element="users-page" context="{{session}}"></dna-view>
<dna-view state="user-detail" element="user-detail" context="{{session}}"></dna-view>
<dna-view state="orders" element="orders-page" context="{{session}}"></dna-view>
<dna-view state="order-detail" element="order-detail" context="{{session}}"></dna-view>
</dna-multi-view>
```

That's kind of a basic idea. My other option was perhaps to add a listener behavior that fired an event from the child element which the parent of the `dna-view` would then respond to with an event fired on the requesting child element with context.

**Comment by Saquib764** [comment]
It seems useful. I'll implement this. :)
However, I suggest you to look for`dna-config` tag. It has `auth` attribute for user authentication. There are other useful attributes in `dna-view`, like `on-auth` and `if-state`.

Cheers!

**Comment by patgmiller** [comment]
Thanks. I saw the user authentication, I like it. However ours is a little more granular than. Each user is assigned to different roles which equates to some ACL stuff. Each user can view most things, but depending on their role they have different edit privileges. 

I am happy to assist with this feature since this is exactly what I am working on for my employer. And based on what I've read in your code I imagine you'd have some useful constructive suggestions for me during the process. 

What kind of structure are you thinking of to handle this? Or is it simply adding a hook which just calls the Polymer methods which handle the data binding?

**Comment by Saquib764** [comment]
Hi,
Sorry for no reply, I was out on a road trip :)

Anyway, since roles are pretty common, I was planning for a `role` attribute in `dna-conf` and `dna-veiw` tags. 

On setting a role for `dna-config`, only states with same role will be visible. Example,

``` script
conf.role = 'admin';

<dna-view state='S1' role='admin' >... </>        // Active
<dna-view state='S1' role='manager' >... </>      // Not active
```

Alternately, you can store role information in global variable i.e `$state`.

**Comment by Saquib764** [comment]
Hi,
Just added `context` attribute to `dna-config` element.
You can use it as follow:

``` script
var conf = document.querySelector('#conf');
conf.context = {
    author: 'Saquib Alam',
    message: 'Star me :)',
}
conf.auth = true;
```

It gets passed to your view element via `$state` variable.

``` script
console.log('context : ', $state.context)
```

Thanks for suggestion :)

**Comment by patgmiller** [comment]
Awesome thanks, I'll give it a try.
