### ISSUE TITLE
sref-active

### ISSUE THREAD

**Issue by mbecker** [Saquib764/dna-router#8]
Hi,

the routing approach seems promising! However how could I determine which view is active to add a class for example to paper-item?

Lets say we have got a normal header navigation with tabs and the user clicks for example a link on the normal page to "profile/xyz" then the tab "Profile" should be highlighted.

Is there a listener to determine which view (or state) is active?

Thanks for your help!

**Comment by Saquib764** [comment]
Hi,
There are listeners in `dna-view` and `dna-many-view`. You can add event listeners to these elements.
Listen for these:
1. page-load-begin
2. page-leave

However, after your issue I just added more event listeners.
Added `page-active` in `dna-view` and `dna-many-view`. This get triggered after page is loaded.
Added added `state-changed` in `dna-config`.

Also, added `on` function to these elements.

``` script
        var conf = document.querySelector('#conf');    // Selects dna-config
        conf.on('state-changed', function(){
            console.log($state);                // Triggers every time state is changed
            // Do your stuff
        })
        var h = document.querySelector('#home');   // Selects a dna-view element
        h.on('page-active', function(e){
            console.log('Home listener')      // Trigers when this view is active
            // Do your stuff
        })
```

`Note`: For woking example see end of `index.html` file in current version. 

PS: Thanks for suggestion :)

**Comment by mbecker** [comment]
Hi,

thank you very much for adding these functions!

For those who have problems to implement the ".on('page-active') listener add the ".querySelector" to the event listener "dom-change":

`app.addEventListener('dom-change', function() {
var h = document.querySelector('#home');
        h.on('page-active', function(e) {
            console.log('Home listener')
        });
    });`

Would be nice if you could update the documentation! ;-)

**Comment by Saquib764** [comment]
Yes I will update documentation :)
